#!/bin/fish

set s "$(string match -q -- "*yes" (pactl get-sink-mute @DEFAULT_SINK@); echo $status)"
#pactl set-sink-mute @DEFAULT_SINK@ $s
wpctl set-mute @DEFAULT_SINK@ $s

dunstify -a "VOLUME" "$(test $s = 1; and echo M; or echo Unm)uted" -i audio-volume-high-symbolic -r 2594 -u normal
